language: node_js
node_js:
  - 10
services:
  - docker
env:
  global:
    - PACT_BROKER_BASE_URL=https://test.pactflow.io
    - PACT_BROKER_PUBLISH_VERIFICATION_RESULTS=true
    # Encrypted PACT_BROKER_TOKEN
    - secure: "KfqDSXWI4OqhFsj0HeVUFJcnUyqVM4EOcAvDG5JejR8kii2qa9pTboqevs9sv/suyVJamer1l/XSXG81z93tux7NvVvH5GJfonmsUP0QOxMniEPlreXoxhu3aWQe17bnemyJEJbeLb9RHGosPorPrUzkCM76hTl7P9QD7/x3FeLm2atu9qk/c/zlS+9zdzMWD+k0AxZQJbIQHGmCuS3ukxlIUZxOqLwzJ/4puQwyk1YD7xM8j6JppNP3tcVSacAgtJYwzQ1nrQNkyw+cxAUdPA5piZnnp1jUswOCcHFoDmzhFc6Fe4Ee8F6QfBn8krW0LpPJwooDRs5EruK57Y/FSfZVJyL3is7SiZ/Z47Eko9TLQdCv8YkM+B8DEQPKZCN4c/9CDJiJwFKhc3RLLyRtNNBNumD8oHsWATG12RYgAduF8khXV/fsgKfQVDYXcoZfj/YQxZLsugqvzRpQfngpmD+/1jxQLWrOG0a5oKUYpn2u3WtNlySZ2SIvhkRWNPCLuGevACyCxS67g2xDPKDkQRBHU+zTZLsGy01bAcllvIN76LuhJizdZ50M4uj6wFOQhtnvUF/72AIk0WLwzNHL9+Cxe4m/au6fQaMOzdHDIad+IiAAt0x0u7AvECCRsTtIJZBCghudLDeVHqL0Iz6EG0tBaWIh9fx+gutTiolU+TI="
before_script:
  - docker pull pactfoundation/pact-cli:latest
script:
  # When a webhook triggers a build, the PACT_URL will be set. In this case, just run the verification step.
  # Otherwise, run the normal build.
  # This is just to get around the fact that Travis CI only has one build definition per repository.
  # Normally you would define a separate job for the webhook triggered verification.
  - >
    if [ -n "${PACT_URL}" ]; then
      make ci_webhook
    else
      make ci
    fi
